
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-02
owner: ucsb-cs156-s25
repo_name: team01-s25-02
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5OTg4MTUw","is_bot":false,"login":"andrew200356","name":"Andrew Wang"},"headRefName":"sw-MenuItemReview-create-db","number":52,"title":"Finishing team01 by adding GET/PUT/DELETE/POST/GET feature for backend and corresponding test","url":"https://github.com/ucsb-cs156-s25/team01-s25-02/pull/52"},{"author":{"id":"U_kgDOBdVC1w","is_bot":false,"login":"Elskin","name":"Xinyan Zhao"},"headRefName":"Xinyan-DiningCommonItem-create-db","number":51,"title":"xz complete controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-02/pull/51"},{"author":{"id":"U_kgDOB3DYsg","is_bot":false,"login":"evaniacheng","name":"evania"},"headRefName":"ec-recommendationRequestController","number":50,"title":"ec - recommendation request controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-02/pull/50"},{"author":{"id":"U_kgDOCNoKew","is_bot":false,"login":"AyalaWang","name":""},"headRefName":"HelpRequestMigrationFile","number":49,"title":"AW-Create Database Table for HelpRequest","url":"https://github.com/ucsb-cs156-s25/team01-s25-02/pull/49"}]
