
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-02
owner: ucsb-cs156-s25
repo_name: team01-s25-02
pull_requests: [{"author":{"id":"U_kgDOBXvSwA","is_bot":false,"login":"jiahuaren","name":"Jiahua Ren"},"headRefName":"jr-delete-put-get","number":57,"title":"jr - created UCSBOrganizationController, add GET (index) and POST (create) and DELETE","url":"https://github.com/ucsb-cs156-s25/team01-s25-02/pull/57"},{"author":{"id":"U_kgDOB3DYsg","is_bot":false,"login":"evaniacheng","name":"evania"},"headRefName":"ec-delete","number":55,"title":"ec - added DELETE endpoint for a specific record in RecommendationRequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-02/pull/55"},{"author":{"id":"U_kgDOB3DYsg","is_bot":false,"login":"evaniacheng","name":"evania"},"headRefName":"ec-put","number":54,"title":"ec -  added PUT (edit) endpoint for a single record in RecommendationRequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-02/pull/54"},{"author":{"id":"U_kgDOB3DYsg","is_bot":false,"login":"evaniacheng","name":"evania"},"headRefName":"ec-get","number":53,"title":"ec - added GET (show) endpoint for a single record in RecommendationRequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-02/pull/53"},{"author":{"id":"U_kgDOCNoKew","is_bot":false,"login":"AyalaWang","name":""},"headRefName":"HelpRequestMigrationFile","number":49,"title":"AW-Create Database Table for HelpRequest","url":"https://github.com/ucsb-cs156-s25/team01-s25-02/pull/49"}]
